# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlarmLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlarmLog(object):
    def setupUi(self, AlarmLog):
        AlarmLog.setObjectName("AlarmLog")
        AlarmLog.resize(1490, 824)
        font = QtGui.QFont()
        font.setPointSize(12)
        AlarmLog.setFont(font)
        self.alarmTable = QtWidgets.QTableWidget(AlarmLog)
        self.alarmTable.setGeometry(QtCore.QRect(470, 60, 511, 591))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alarmTable.setFont(font)
        self.alarmTable.setAlternatingRowColors(True)
        self.alarmTable.setObjectName("alarmTable")
        self.alarmTable.setColumnCount(4)
        self.alarmTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.alarmTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.alarmTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.alarmTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.alarmTable.setHorizontalHeaderItem(3, item)
        

        self.retranslateUi(AlarmLog)
        QtCore.QMetaObject.connectSlotsByName(AlarmLog)

    def retranslateUi(self, AlarmLog):
        _translate = QtCore.QCoreApplication.translate
        AlarmLog.setWindowTitle(_translate("AlarmLog", "Alarm Log"))
        item = self.alarmTable.horizontalHeaderItem(0)
        item.setText(_translate("AlarmLog", "Time"))
        item = self.alarmTable.horizontalHeaderItem(1)
        item.setText(_translate("AlarmLog", "Sensor"))
        item = self.alarmTable.horizontalHeaderItem(2)
        item.setText(_translate("AlarmLog", "Value"))
        item = self.alarmTable.horizontalHeaderItem(3)
        item.setText(_translate("AlarmLog", "Alarm Type"))
