# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1498, 924)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(380, 150, 711, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(771, 16777215))
        self.tableWidget.setBaseSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(4, 0, item)
        
        # Create all missing table items for the 5x4 grid
        for row in range(5):
            for col in range(4):
                if self.tableWidget.item(row, col) is None:
                    item = QtWidgets.QTableWidgetItem()
                    self.tableWidget.setItem(row, col, item)
        
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(175)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 710, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plot_tmp = QtWidgets.QWidget(self.centralwidget)
        self.plot_tmp.setGeometry(QtCore.QRect(30, 470, 281, 191))
        self.plot_tmp.setObjectName("plot_tmp")
        self.plot_vibs = QtWidgets.QWidget(self.centralwidget)
        self.plot_vibs.setGeometry(QtCore.QRect(320, 470, 281, 191))
        self.plot_vibs.setObjectName("plot_vibs")
        self.plot_speed = QtWidgets.QWidget(self.centralwidget)
        self.plot_speed.setGeometry(QtCore.QRect(610, 470, 281, 191))
        self.plot_speed.setObjectName("plot_speed")
        self.plot_pressure = QtWidgets.QWidget(self.centralwidget)
        self.plot_pressure.setGeometry(QtCore.QRect(900, 470, 281, 191))
        self.plot_pressure.setObjectName("plot_pressure")
        self.plot_curr = QtWidgets.QWidget(self.centralwidget)
        self.plot_curr.setGeometry(QtCore.QRect(1190, 470, 281, 191))
        self.plot_curr.setObjectName("plot_curr")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(610, 70, 231, 51))
        
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(650, 800, 221, 51))
        self.button.setObjectName("button")
        self.button.setText("View Alarm Log")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button.setFont(font)
        
        self.pushButton_mute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mute.setGeometry(QtCore.QRect(400, 800, 221, 51))
        self.pushButton_mute.setObjectName("pushButton_mute")
        self.pushButton_mute.setText("Mute")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_mute.setFont(font)
        
        
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 13, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 13, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1498, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        

        self.retranslateUi(MainWindow)
        
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        
        MainWindow.setWindowTitle("Dashboard")
        
        # Headers - remove translation
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText("Timestamp")
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText("Reading")
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText("Status")
        
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        
        # Row 0: Temperature sensor
        item = self.tableWidget.item(0, 0)
        item.setText("Temperature")
        item = self.tableWidget.item(0, 1)
        
        # Row 1: Vibration sensor
        item = self.tableWidget.item(1, 0)
        item.setText("Vibration")
        
        # Row 2: Speed sensor
        item = self.tableWidget.item(2, 0)
        item.setText("Speed")
        
        # Row 3: Pressure sensor
        item = self.tableWidget.item(3, 0)
        item.setText("Pressure")
        
        # Row 4: Current sensor
        item = self.tableWidget.item(4, 0)
        item.setText("Current")
        
        
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        
        # Labels
        self.label.setText("Overall System Status : ")
        self.title.setText("Sensors' Readings")

